// App Upgrade #2: sample GIS data for locating outdoor exercise equipment.
// The official GIS dataset will be provided at a later stage; these sample sites
// (real LCSD parks with elderly fitness corners) let the feature run locally.
export const EQUIPMENT_LOCATIONS = [
	{
		id: "1",
		nameEn: "Victoria Park Fitness Corner",
		nameZh: "維多利亞公園長者健身角",
		districtEn: "Causeway Bay, Hong Kong Island",
		districtZh: "香港島 銅鑼灣",
		latitude: 22.2819,
		longitude: 114.1878,
		types: ["aerobic", "muscle", "mobility"],
	},
	{
		id: "2",
		nameEn: "Kowloon Park Fitness Trail",
		nameZh: "九龍公園健身徑",
		districtEn: "Tsim Sha Tsui, Kowloon",
		districtZh: "九龍 尖沙咀",
		latitude: 22.3003,
		longitude: 114.1699,
		types: ["muscle", "balance", "multifunctional"],
	},
	{
		id: "3",
		nameEn: "Sha Tin Park Elderly Fitness Corner",
		nameZh: "沙田公園長者健身角",
		districtEn: "Sha Tin, New Territories",
		districtZh: "新界 沙田",
		latitude: 22.3806,
		longitude: 114.1899,
		types: ["aerobic", "mobility", "relaxation"],
	},
	{
		id: "4",
		nameEn: "Tuen Mun Park Fitness Corner",
		nameZh: "屯門公園健身角",
		districtEn: "Tuen Mun, New Territories",
		districtZh: "新界 屯門",
		latitude: 22.3908,
		longitude: 113.9725,
		types: ["balance", "muscle", "wheelchair"],
	},
	{
		id: "5",
		nameEn: "Lai Chi Kok Park Fitness Corner",
		nameZh: "荔枝角公園健身角",
		districtEn: "Lai Chi Kok, Kowloon",
		districtZh: "九龍 荔枝角",
		latitude: 22.3374,
		longitude: 114.1418,
		types: ["aerobic", "mobility", "upper", "lower"],
	},
	{
		id: "6",
		nameEn: "Quarry Bay Park Fitness Corner",
		nameZh: "鰂魚涌公園健身角",
		districtEn: "Quarry Bay, Hong Kong Island",
		districtZh: "香港島 鰂魚涌",
		latitude: 22.2896,
		longitude: 114.2222,
		types: ["muscle", "multifunctional", "relaxation"],
	},
	{
		id: "7",
		nameEn: "Tsing Yi Park Fitness Corner",
		nameZh: "青衣公園健身角",
		districtEn: "Tsing Yi, New Territories",
		districtZh: "新界 青衣",
		latitude: 22.3506,
		longitude: 114.0999,
		types: ["balance", "mobility", "wheelchair"],
	},
	{
		id: "8",
		nameEn: "Morse Park Fitness Corner",
		nameZh: "摩士公園健身角",
		districtEn: "Wong Tai Sin, Kowloon",
		districtZh: "九龍 黃大仙",
		latitude: 22.3421,
		longitude: 114.1932,
		types: ["aerobic", "muscle", "lower"],
	},
];
