export const loginTranslations = {
	en: {
		loginTitle: "Log In",
		loginSubtitle: "Sign in to access all features, or continue as guest for limited access.",
		loginIdentifier: "Phone or Email",
		loginIdentifierPlaceholder: "Enter phone number or email",
		loginIdentifierHint: "You can log in with your phone number. If you registered an email, you may also use your email.",
		name: "Full Name",
		namePlaceholder: "Enter your full name",
		phone: "Phone Number",
		phonePlaceholder: "Enter 8-digit phone number",
		email: "Email (Optional)",
		emailPlaceholder: "Enter email address",
		role: "Role",
		rolePlaceholder: "Select your role",
		profileRole_participant: "Participant",
		profileRole_staff: "Programme Staff",
		profileRole_caregiver: "Caregiver",
		password: "Password",
		passwordPlaceholder: "Enter password",
		loginButton: "Log In",
		guestButton: "Continue as Guest",
		loginRequired: "Please enter your phone or email and password.",
		invalidCredentials: "Invalid phone/email or password.",
		invalidPhone: "Please enter a valid 8-digit phone number.",
		invalidEmail: "Please enter a valid email address.",
		emailNotRegistered: "This email was not registered. Please log in with your phone number.",
		phoneExists: "This phone number is already registered.",
		emailExists: "This email is already registered.",
		nameRequired: "Please enter your name.",
		roleRequired: "Please select a role.",
		phoneRequired: "Please enter your phone number.",
		logout: "Log Out",
		logoutConfirm: "Are you sure you want to log out?",
		cancel: "Cancel",
		confirm: "Confirm",
		loggedInAs: "Logged in as",
		guestMode: "Guest mode",
		loginNow: "Log In Now",
		loginNowHint: "Sign in to unlock all features.",
		registerTitle: "Create Account",
		registerSubtitle: "Register to access all features in the app.",
		confirmPassword: "Confirm Password",
		confirmPasswordPlaceholder: "Re-enter password",
		registerButton: "Register",
		hasAccount: "Already have an account?",
		goToLogin: "Log in",
		noAccount: "Don't have an account?",
		goToRegister: "Register now",
		registerRequired: "Please fill in all fields.",
		passwordTooShort: "Password must be at least 6 characters.",
		passwordMismatch: "Passwords do not match.",
		usernameExists: "This username is already taken.",
		usernameReserved: "This username is reserved.",
		accountPhone: "Phone",
		accountRole: "Role",
		registerSuccess: "Registration successful. Welcome!",
		guestRestrictedTitle: "Login Required",
		guestRestrictedMessage: "Guest mode only allows access to some videos and audio guides. Please log in to use this feature.",
		guestRestrictedSection: "Log in to view full content",
		guestModeBanner: "You are browsing as a guest. Only some videos and audio guides are available.",
		guestLocked: "Login required",
		guestConfirmTitle: "Continue as Guest?",
		guestConfirmMessage:
			"You are entering Guest mode. Some features will be unavailable (session record, goals, group chat, map, usage data, risk, location, research, favorites). Only part of the outdoor equipment videos and audio guides can be used. Please log in for full access.",
		stayGuest: "Continue as Guest",
		forgotPassword: "Forgot password?",
		forgotPasswordTitle: "Reset Password",
		forgotPasswordSubtitle: "Enter your registered phone number or email to receive a verification code.",
		forgotPasswordStep2Subtitle: "Enter the verification code and set a new password.",
		forgotPasswordDemoNote: "Demo mode: no SMS/email is sent. A sample verification code will be shown on screen.",
		sendCodeButton: "Send Verification Code",
		resendCodeButton: "Resend Code",
		resetPasswordButton: "Reset Password",
		verificationCode: "Verification Code",
		verificationCodePlaceholder: "Enter 6-digit code",
		newPassword: "New Password",
		backToLogin: "Back to log in",
		resetIdentifierRequired: "Please enter your phone number or email.",
		accountNotFound: "No account found with this phone number or email.",
		resetRequired: "Please fill in the verification code and new password.",
		invalidCode: "Invalid verification code.",
		codeExpired: "The verification code has expired. Please request a new one.",
		codeSentTitle: "Verification Code Sent",
		codeSentDemoMessage: "Demo: a code has been “sent” to your %{channel}.\nSample code: %{code}",
		codeSentTo: "Code sent to your %{channel}: %{target}",
		demoCodeLabel: "Demo code",
		emailChannel: "email",
		phoneChannel: "phone",
		resetSuccess: "Password reset successfully. Please log in with your new password.",
	},
	zh: {
		loginTitle: "登入",
		loginSubtitle: "登入以使用全部功能，或以訪客身份繼續（部分功能受限）。",
		loginIdentifier: "手機號碼或電郵",
		loginIdentifierPlaceholder: "請輸入手機號碼或電郵",
		loginIdentifierHint: "可使用手機號碼登入；如註冊時填寫了電郵，亦可使用電郵登入。",
		name: "姓名",
		namePlaceholder: "請輸入姓名",
		phone: "手機號碼",
		phonePlaceholder: "請輸入8位手機號碼",
		email: "電郵（選填）",
		emailPlaceholder: "請輸入電郵地址",
		role: "角色",
		rolePlaceholder: "請選擇角色",
		profileRole_participant: "參與者",
		profileRole_staff: "項目人員",
		profileRole_caregiver: "照顧者",
		password: "密碼",
		passwordPlaceholder: "請輸入密碼",
		loginButton: "登入",
		guestButton: "以訪客身份繼續",
		loginRequired: "請輸入手機號碼或電郵及密碼。",
		invalidCredentials: "手機號碼/電郵或密碼不正確。",
		invalidPhone: "請輸入有效的8位手機號碼。",
		invalidEmail: "請輸入有效的電郵地址。",
		emailNotRegistered: "此電郵尚未註冊，請使用手機號碼登入。",
		phoneExists: "此手機號碼已被註冊。",
		emailExists: "此電郵已被註冊。",
		nameRequired: "請輸入姓名。",
		roleRequired: "請選擇角色。",
		phoneRequired: "請輸入手機號碼。",
		logout: "登出",
		logoutConfirm: "確定要登出嗎？",
		cancel: "取消",
		confirm: "確定",
		loggedInAs: "目前登入",
		guestMode: "訪客模式",
		loginNow: "立即登入",
		loginNowHint: "登入後可使用全部功能。",
		registerTitle: "註冊帳戶",
		registerSubtitle: "註冊後可使用應用程式的全部功能。",
		confirmPassword: "確認密碼",
		confirmPasswordPlaceholder: "請再次輸入密碼",
		registerButton: "註冊",
		hasAccount: "已有帳戶？",
		goToLogin: "前往登入",
		noAccount: "還沒有帳戶？",
		goToRegister: "立即註冊",
		registerRequired: "請填寫所有欄位。",
		passwordTooShort: "密碼至少需要 6 個字元。",
		passwordMismatch: "兩次輸入的密碼不一致。",
		usernameExists: "此用戶名稱已被使用。",
		usernameReserved: "此用戶名稱已被保留。",
		accountPhone: "手機",
		accountRole: "角色",
		registerSuccess: "註冊成功，歡迎使用！",
		guestRestrictedTitle: "需要登入",
		guestRestrictedMessage: "訪客模式僅可瀏覽部分影片及語音指導。請登入以使用此功能。",
		guestRestrictedSection: "登入後可查看完整內容",
		guestModeBanner: "您目前以訪客身份瀏覽，僅可使用部分影片及語音指導。",
		guestLocked: "需要登入",
		guestConfirmTitle: "以訪客模式繼續？",
		guestConfirmMessage:
			"您即將進入訪客模式。部分功能將無法使用（運動記錄、目標設定、群組訊息、器材地圖、使用數據、風險管理、設施位置、大學研究、收藏）。僅可使用部分戶外器材的影片及語音指導。登入後可使用全部功能。",
		stayGuest: "繼續訪客模式",
		forgotPassword: "忘記密碼？",
		forgotPasswordTitle: "重設密碼",
		forgotPasswordSubtitle: "請輸入已註冊的手機號碼或電郵，以接收驗證碼。",
		forgotPasswordStep2Subtitle: "請輸入驗證碼並設定新密碼。",
		forgotPasswordDemoNote: "示範模式：不會真正發送短訊或電郵，驗證碼會直接顯示在畫面上。",
		sendCodeButton: "發送驗證碼",
		resendCodeButton: "重新發送驗證碼",
		resetPasswordButton: "重設密碼",
		verificationCode: "驗證碼",
		verificationCodePlaceholder: "請輸入6位驗證碼",
		newPassword: "新密碼",
		backToLogin: "返回登入",
		resetIdentifierRequired: "請輸入手機號碼或電郵。",
		accountNotFound: "找不到與此手機號碼或電郵相關的帳戶。",
		resetRequired: "請填寫驗證碼及新密碼。",
		invalidCode: "驗證碼不正確。",
		codeExpired: "驗證碼已過期，請重新獲取。",
		codeSentTitle: "驗證碼已發送",
		codeSentDemoMessage: "示範：驗證碼已「發送」至您的%{channel}。\n示例驗證碼：%{code}",
		codeSentTo: "驗證碼已發送至您的%{channel}：%{target}",
		demoCodeLabel: "示例驗證碼",
		emailChannel: "電郵",
		phoneChannel: "手機",
		resetSuccess: "密碼重設成功，請使用新密碼登入。",
	},
};
