// Translations for the App Upgrade features (#1 - #11)
export const upgradeTranslations = {
	en: {
		// #1 Login
		login: "Log in",
		loginTitle: "Welcome to OUTDOOR FIT",
		username: "Username",
		password: "Password",
		loginButton: "Log in",
		registerButton: "Register",
		guestButton: "Continue as Guest",
		guestNotice: "Guest mode: you can only access some videos and audio instructions. Log in for full access to all functions.",
		guestBlockedTitle: "Login required",
		guestBlockedMessage: "Guest accounts can only access some videos and audio instructions. Please log in to unlock all content.",
		goLogin: "Go to Log in",
		stayGuest: "Stay as Guest",
		logout: "Log out",
		loggedInAs: "Logged in as",
		guestUser: "Guest",
		userExists: "This username is already registered. Please log in.",
		wrongCredentials: "Incorrect username or password.",
		emptyFields: "Please enter a username and password.",
		autoLogoutNotice: "You will be automatically logged out after 1.5 hours of inactivity.",

		// #2 Locate equipment (GIS)
		equipmentMap: "Locate Equipment",
		equipmentMapNote: "Official GIS data will be provided at a later stage. The list below shows sample locations.",
		filterByType: "Filter by equipment type",
		openInMaps: "Open in Maps",
		distanceNote: "District",

		// #4 Usage data
		usageData: "My Usage Data",
		usageDaysUsed: "Total days the app was used",
		usageLoginEvents: "Total log-in events",
		usageIntroLoads: "Exercise introduction pages loaded",
		usageAudioPlays: "Audio recordings played",
		usageGoalsAchieved: "Goals achieved (incl. WHO recommendations)",
		usageOutdoorSessions: "Outdoor practical sessions completed",
		usageHomeSessions: "Home practical sessions completed",
		usageTtsPlays: "Text-to-speech played",
		times: "times",
		days: "days",

		// #5 Session record
		sessionRecord: "Session Record",
		sessionLog: "Session Log",
		start: "Start",
		pause: "Pause",
		resume: "Resume",
		endSession: "End Session",
		sessionMode: "Where is this session?",
		outdoorSession: "Outdoor session",
		homeSession: "Home session",
		sessionSummary: "Session Summary",
		completionTime: "Date and time of completion",
		totalDuration: "Total session duration",
		emotionScale: "How do you feel? (Emotion scale)",
		rpeScale: "Rate of perceived exertion (0 = rest, 10 = maximal)",
		showMore: "Show more",
		showLess: "Show less",
		sessionJournal: "Session journal",
		journalPlaceholder: "Record your personal feelings after the session...",
		exerciseTypeRecord: "Exercise type record",
		exerciseTypeRecordHint: "Take a photo of the equipment or its instruction board so the app can recognize the exercise. Reps must be added manually. (Not required for home sessions)",
		takePhoto: "Take a photo to recognize",
		photoRecognized: "Recognized exercise",
		chooseEquipment: "Confirm the recognized equipment",
		reps: "Reps",
		addExercise: "Add exercise",
		removeExercise: "Remove",
		typeChecklist: "Exercise done in this session",
		aerobicDone: "Aerobic exercise",
		balanceDone: "Balance exercise",
		muscleDone: "Muscle strengthening",
		weeklyGoalProgress: "Weekly goal progress",
		saveAndContinue: "Save and Continue",
		sessionSaved: "Session saved!",
		goalAchievedMsg: "Congratulations! You achieved a weekly goal!",
		noSessions: "No recorded sessions yet",
		share: "Share",
		shareToGroup: "Share to Group",
		shareToExternal: "Share to other apps",
		sessionSharedToGroup: "Session shared to the group!",
		exercisesDone: "Exercises done",
		discardSession: "Discard",
		discardSessionConfirm: "Discard this session without saving?",

		// #6 Goals
		goalSetting: "Goal Setting",
		presetGoals: "Weekly preset goals",
		aerobicGoal: "Aerobic exercise",
		balanceGoal: "Balance exercise",
		muscleGoal: "Muscle strengthening",
		targetDays: "Target days per week",
		daysPerWeek: "days / week",
		adjustTarget: "Adjust the target number of days according to your own capacity.",
		smartGoal: "SMART Goal",
		smartGoals: "My SMART Goals",
		addSmartGoal: "Add SMART goal",
		smartPlaceholder: "e.g. Walk 30 minutes in the park, 3 times this week",
		smartGuidanceTitle: "How to write a SMART goal",
		smartGuidance:
			"S - Specific: state clearly what you will do, e.g. \"walk in the park\".\nM - Measurable: include numbers, e.g. \"30 minutes, 3 times a week\".\nA - Achievable: set a goal within your current ability.\nR - Relevant: the goal should matter to your health.\nT - Time-bound: set a time frame, e.g. \"this week\".\n\nExample: \"This week I will use the fitness bike in the park for 20 minutes on Monday, Wednesday and Friday.\"",
		keepSameGoals: "Keep the same goals for this week",
		goalsCarriedOver: "Last week's goals have been copied to this week.",
		noSmartGoals: "No SMART goals for this week yet",
		markDone: "Done",
		weeklyCalendar: "This Week",
		saved: "Saved",

		// #7 SMS / group chat & #8 chatbot
		groupChat: "Group Chat",
		messagePlaceholder: "Type a message...",
		send: "Send",
		attachPhoto: "Photo",
		chatbotName: "FIT Leader Bot",
		staffName: "Programme Staff",
		meName: "Me",
		chatWelcome:
			"Welcome to the OUTDOOR FIT group! Share your goal progress and photos, and cheer for each other!",
		mondayMessage:
			"Good Monday morning! This is a new week — please remember to follow the weekly goals you have set up for yourself! Be encouraged to show photos of the equipment you've used and your goal progress to all the group members!",
		botFallback:
			"Thanks for your message! I can answer questions about the app (e.g. \"How do I record a session?\", \"How do I set goals?\"). Programme staff will follow up on other questions.",
		sharedSessionTitle: "I completed an exercise session!",
		sharedSessionTag: "Exercise session",
		resetOnboarding: "Reset onboarding",
		resetOnboardingConfirm:
			"Clear Start / disclaimer progress and log out? The Start screen and disclaimer will show again.",
		resetOnboardingDone: "Onboarding has been reset.",

		// #10 Learning progress
		learningProgress: "Learning Progress",
		readMaterial: "Text read",
		watchedVideo: "Video watched",
		listenedAudio: "Audio listened",
		learningProgressHint: "Learning records of your favorite items",
		notStarted: "Not started",

		// #11 TTS
		readAloud: "Read aloud",
		stopReading: "Stop reading",

		// misc
		statistics: "Usage Data",
		cancel: "Cancel",
		confirm: "Confirm",
		delete: "Delete",
		deleteSessionConfirm: "Delete this session record?",
	},
	zh: {
		// #1 登入
		login: "登入",
		loginTitle: "歡迎使用戶外健身應用",
		username: "用戶名稱",
		password: "密碼",
		loginButton: "登入",
		registerButton: "註冊",
		guestButton: "以訪客身份繼續",
		guestNotice: "訪客模式：只能觀看部分影片及語音指導。登入後可使用全部功能。",
		guestBlockedTitle: "需要登入",
		guestBlockedMessage: "訪客帳戶只能觀看部分影片及語音指導。請登入以解鎖全部內容。",
		goLogin: "前往登入",
		stayGuest: "繼續訪客模式",
		logout: "登出",
		loggedInAs: "目前登入",
		guestUser: "訪客",
		userExists: "此用戶名稱已註冊，請直接登入。",
		wrongCredentials: "用戶名稱或密碼不正確。",
		emptyFields: "請輸入用戶名稱及密碼。",
		autoLogoutNotice: "如90分鐘內沒有操作，系統會自動登出。",

		// #2 器材定位 (GIS)
		equipmentMap: "尋找器材",
		equipmentMapNote: "官方GIS數據將於稍後階段提供，以下為示範地點。",
		filterByType: "按器材類型篩選",
		openInMaps: "在地圖中打開",
		distanceNote: "地區",

		// #4 使用數據
		usageData: "我的使用數據",
		usageDaysUsed: "應用程式使用總天數",
		usageLoginEvents: "登入次數",
		usageIntroLoads: "運動介紹頁面瀏覽次數",
		usageAudioPlays: "語音指導播放次數",
		usageGoalsAchieved: "達成目標次數（包括世衞建議）",
		usageOutdoorSessions: "完成戶外運動時段",
		usageHomeSessions: "完成家居運動時段",
		usageTtsPlays: "文字轉語音播放次數",
		times: "次",
		days: "天",

		// #5 運動時段記錄
		sessionRecord: "運動記錄",
		sessionLog: "運動日誌",
		start: "開始",
		pause: "暫停",
		resume: "繼續",
		endSession: "結束時段",
		sessionMode: "本次運動地點？",
		outdoorSession: "戶外運動",
		homeSession: "家居運動",
		sessionSummary: "時段總結",
		completionTime: "完成日期及時間",
		totalDuration: "總時長",
		emotionScale: "你現在的心情如何？（情緒量表）",
		rpeScale: "自覺竭力程度（0 = 休息，10 = 極限）",
		showMore: "顯示更多",
		showLess: "收起",
		sessionJournal: "運動日記",
		journalPlaceholder: "記錄運動後的個人感受...",
		exerciseTypeRecord: "運動類型記錄",
		exerciseTypeRecordHint: "拍攝器材或說明板的照片，應用程式可識別運動並自動輸入名稱。次數需手動填寫。（家居運動無需填寫）",
		takePhoto: "拍照識別器材",
		photoRecognized: "已識別運動",
		chooseEquipment: "確認識別到的器材",
		reps: "次數",
		addExercise: "新增運動",
		removeExercise: "移除",
		typeChecklist: "本時段完成的運動類型",
		aerobicDone: "帶氧運動",
		balanceDone: "平衡運動",
		muscleDone: "肌肉強化",
		weeklyGoalProgress: "每週目標進度",
		saveAndContinue: "儲存並繼續",
		sessionSaved: "時段已儲存！",
		goalAchievedMsg: "恭喜！你達成了一個每週目標！",
		noSessions: "暫時沒有運動記錄",
		share: "分享",
		shareToGroup: "分享到群組",
		shareToExternal: "分享到其他應用",
		sessionSharedToGroup: "已分享到群組！",
		exercisesDone: "完成的運動",
		discardSession: "放棄",
		discardSessionConfirm: "放棄本次時段而不儲存？",

		// #6 目標
		goalSetting: "目標設定",
		presetGoals: "每週預設目標",
		aerobicGoal: "帶氧運動",
		balanceGoal: "平衡運動",
		muscleGoal: "肌肉強化",
		targetDays: "每週目標天數",
		daysPerWeek: "天／週",
		adjustTarget: "可根據自己的能力調整目標天數。",
		smartGoal: "SMART目標",
		smartGoals: "我的SMART目標",
		addSmartGoal: "新增SMART目標",
		smartPlaceholder: "例如：本週在公園步行30分鐘，共3次",
		smartGuidanceTitle: "如何撰寫SMART目標",
		smartGuidance:
			"S - 具體（Specific）：清楚說明要做什麼，例如「在公園步行」。\nM - 可量度（Measurable）：加入數字，例如「每次30分鐘，每週3次」。\nA - 可達成（Achievable）：設定在自己能力範圍內的目標。\nR - 相關（Relevant）：目標應與你的健康有關。\nT - 有時限（Time-bound）：設定時間範圍，例如「本週內」。\n\n例子：「本週一、三、五在公園使用健身單車各20分鐘。」",
		keepSameGoals: "沿用上週目標",
		goalsCarriedOver: "已把上週目標複製到本週。",
		noSmartGoals: "本週還沒有SMART目標",
		markDone: "完成",
		weeklyCalendar: "本週",
		saved: "已儲存",

		// #7 群組訊息 & #8 聊天機械人
		groupChat: "群組訊息",
		messagePlaceholder: "輸入訊息...",
		send: "發送",
		attachPhoto: "相片",
		chatbotName: "FIT組長機械人",
		staffName: "計劃職員",
		meName: "我",
		chatWelcome: "歡迎加入戶外健身群組！請分享你的目標進度和相片，互相鼓勵！",
		mondayMessage:
			"星期一早晨！新的一週開始了——請記得跟隨你為自己訂立的每週目標！歡迎向組員分享你使用過的器材相片和目標進度！",
		botFallback:
			"多謝你的訊息！我可以解答關於應用程式的問題（例如「如何記錄運動？」、「如何設定目標？」）。其他問題計劃職員會跟進。",
		sharedSessionTitle: "我完成了一節運動！",
		sharedSessionTag: "運動記錄",
		resetOnboarding: "重置引導",
		resetOnboardingConfirm: "確定清除 Start／免責聲明進度並登出？之後會再次顯示 Start 與免責聲明。",
		resetOnboardingDone: "引導已重置。",

		// #10 學習進度
		learningProgress: "學習進度",
		readMaterial: "已閱讀文字",
		watchedVideo: "已觀看影片",
		listenedAudio: "已收聽語音",
		learningProgressHint: "收藏項目的學習記錄",
		notStarted: "未開始",

		// #11 文字轉語音
		readAloud: "朗讀內容",
		stopReading: "停止朗讀",

		// 其他
		statistics: "使用數據",
		cancel: "取消",
		confirm: "確認",
		delete: "刪除",
		deleteSessionConfirm: "刪除此運動記錄？",
	},
};
